development:
  adapter: mysql2
  encoding: utf8
  database: hostastic_dev
  username: root
  password: "123456"

test:
  adapter: mysql2
  encoding: utf8
  database: hostastic_test
  username: root
  password: "123456"
